### PR TITLE
Moved controller and Flask Server instantiation and tear down to appr…

### PR DESCRIPTION
**Pull request by andrewtran1995**
…opriate unittest functions (setUp, tearDown); fixed termination of controller and Flask Server

### CODE REVIEW

**Comment by joyoyoyoyoyo** [comment]
Is the test passing on your local machine or the jetson?

**Comment by andrewtran1995** [comment]
It's passing on my local machine -- is it not working on the Jetson?

**Comment by joyoyoyoyoyo** [comment]
@andrewtran1995 It should be working, but I just wasn't able to verify because the machine I was using couldn't run it. I was on a public computer.

**Comment by andrewtran1995** [comment]
Noticed it doesn't work on the Jetson, perhaps due to how process group IDs work on there as opposed to my local machine. I'll have to edit this to allow for a more widespread solution.

**Pull request merged**
